### ISSUE TITLE
Is it possible to also send the link to the participant's email?

### ISSUE THREAD

**Issue by crescendochu** [crescendochu/access-survey#15]
<img width="659" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/50616f33-103c-44a1-baab-40dd29b8a8c9">

**Comment by rrrrrrockpang** [comment]
Remove the resume URL: f4b35a09936cca2c502ef0f2d05bee2da4b7b301

**Comment by rrrrrrockpang** [comment]
Still need to look into sending the URL to email...

**Comment by rrrrrrockpang** [comment]
@crescendochu Seem to be a lot of work :) https://stackoverflow.com/questions/55795125/how-to-send-email-from-my-react-web-application

**Comment by crescendochu** [comment]
Donnnnnne! 3fdada9789ad8ae6a39b7d4e89774b080cdefc46
