### ISSUE TITLE
What's the difference between answeredMobilityAids and mobilityAidOptions?

### ISSUE THREAD

**Issue by crescendochu** [crescendochu/access-survey#19]
<img width="460" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/f886df95-69df-4e44-a2d6-93e7ccc0158d">

**Comment by rrrrrrockpang** [comment]
`answeredMobilityAids` is the mobilityaids that have been answered. 

For example, if I chose three mobility aids (`mobilityAidOptions`), then I finished the first one (e.g., crutches). Then `answeredMobilityAids = ["Crutches"]`. If user comes back later, we identify `Crutches` have been answered, we can updte `mobilityAid = "Walker"`

**Comment by crescendochu** [comment]
Thank you!
