### ISSUE TITLE
This one is still broken

### ISSUE THREAD

**Issue by crescendochu** [crescendochu/access-survey#27]
<img width="1112" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/209843b7-d8b7-47a6-9613-fc4982c92e72">

**Comment by rrrrrrockpang** [comment]
Where is broken?

**Comment by rrrrrrockpang** [comment]
Do you mean here? That's the MaterialUI effect 👎 

<img width="47" alt="Screen Shot 2024-07-05 at 5 12 55 PM" src="https://github.com/crescendochu/access-survey/assets/73901780/63cef032-9110-49db-be7a-8c44802aaa4c">

**Comment by crescendochu** [comment]
LMAO I can fix it no worries

**Comment by crescendochu** [comment]
Done! Fixed via 7bb2a966657777ce4a7d48e276aa87641ff7cb0b
