### ISSUE TITLE
Bug in validating Question 3

### ISSUE THREAD

**Issue by crescendochu** [crescendochu/access-survey#29]
<img width="1312" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/92daf5fc-0c9a-4134-bf0b-c10390d1c34f">

**Comment by crescendochu** [comment]
@rrrrrrockpang I can't figure this out :(

**Comment by rrrrrrockpang** [comment]
The state variable `answers` is not updated before calling the validate function. Add useEffect to make sure validate after state variables are updated.

**Comment by crescendochu** [comment]
Thank youuuu! There is still a bug... if you don't select anything at first, then make a selection, it does not advance to the next step :(

**Comment by rrrrrrockpang** [comment]
Resolved cefd7e4ab4b0a37ebd716795458676151d2000cd
