### ISSUE TITLE
Question 3 type box broken

### ISSUE THREAD

**Issue by crescendochu** [crescendochu/access-survey#3]
<img width="1111" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/11b72820-cd0c-4ccd-8cc9-0e2d91f8b8e7">

**Comment by rrrrrrockpang** [comment]
CSS issue. TODO later.

**Comment by rrrrrrockpang** [comment]
* Adjusted the MaterialUI default behavior. 
* Adjust button position as well as navigation button position (up/down buttons)
