### ISSUE TITLE
Add a section break after each of the image groups

### ISSUE THREAD

**Issue by crescendochu** [crescendochu/access-survey#44]
<img width="810" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/c9d1a2c1-7b07-4abc-b6fd-888a6cfb5696">

**Comment by crescendochu** [comment]
Actually given how we cut down the number of images, I think we need a section divider every three groups

**Comment by rrrrrrockpang** [comment]
<img width="1424" alt="Screen Shot 2024-07-12 at 1 09 04 AM" src="https://github.com/user-attachments/assets/580ff585-c57a-4a4c-af23-6784d1079528">

Would something like this work? The issue is that if we make it a full page it'll mess up with the step number.

**Comment by rrrrrrockpang** [comment]
What does the save and continue later do?

**Comment by rrrrrrockpang** [comment]
The redirect functions is working (2eb1e4a419dad8281889d52c4ca64d0dd721880a), but there are two issues
1. `calculateCompletedGroups` fails to return a number
2. @crescendochu Need to verify the new URL redirects to the current image.

**Comment by crescendochu** [comment]
new URL redirecting is doing something weird with the randomization

**Comment by rrrrrrockpang** [comment]
The redirected URL tracks the image selection and image comparison now. 0eea947c4ebab5224c941692f2cc1d2ec45af089

Issues: 
* The question starts from 9 instead of 16?

**Comment by rrrrrrockpang** [comment]
Fix c3d9118b3761507350cc28bd72ce7f21bad6a92e
