### ISSUE TITLE
Implement survey retrieval at a later time

### ISSUE THREAD

**Issue by crescendochu** [crescendochu/access-survey#6]
<img width="1284" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/f9450d96-94e8-4ed5-ae12-0cad5ed3c5e1">

**Comment by rrrrrrockpang** [comment]
Enable this c8dfd9b82e0b66247a1955ca2611512cac9bc776

Issue needs to be tested: 
* the mobility aid could be messed up if you alternate (e.g., finish 1 and then rate the rest of 3 later). Needs to test if this is the case.

**Comment by crescendochu** [comment]
I chose walker, mobility scooter and motorized wheelchair, after doing image selections for walker and mobility scooter, this screen still says mobility scooter and motorized wheelchair. 
<img width="1728" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/91ead194-a6ec-4b86-be06-451b6b0a69c4">

**Comment by crescendochu** [comment]
and this is what happens if I hit continue, looks like its stuck on mobility scooter and never able to move forward 
<img width="1728" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/3c49fff8-1b6b-4824-8163-258a0001795e">

**Comment by crescendochu** [comment]
I tested with 2 options choosing 'walker' and 'crutches', so by end of round one I get first image below, but when I retrieved using the link its still showing walker [http://localhost:3000/resume-survey/a8NpqYycYCMLqdErHnRF](http://localhost:3000/resume-survey/a8NpqYycYCMLqdErHnRF)
<img width="1726" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/88fd10fe-6919-4d38-b299-f6d2b96d487e">
<img width="1728" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/89749698-d262-4d31-958c-5f0967167c15">

**Comment by rrrrrrockpang** [comment]
Resolved at 630e4f6
