### ISSUE TITLE
Implement drag and drop question

### ISSUE THREAD

**Issue by crescendochu** [crescendochu/access-survey#7]
<img width="771" alt="image" src="https://github.com/crescendochu/access-survey/assets/60413478/2bc271e7-9c40-40df-b10c-e42e7d38553d">

Figma link: [https://www.figma.com/design/aEeQBzg1lqoIi2a8zQHYn4/Access-Survey-Image-Selection?node-id=185-226](https://www.figma.com/design/aEeQBzg1lqoIi2a8zQHYn4/Access-Survey-Image-Selection?node-id=185-226)
Tyeform example link: [https://0c241h8elga.typeform.com/to/ZOEfkMKl](https://0c241h8elga.typeform.com/to/ZOEfkMKl)

**Comment by rrrrrrockpang** [comment]
Add to TODO. Is there a React library for this?

**Comment by crescendochu** [comment]
[https://www.npmjs.com/package/react-beautiful-dnd](https://www.npmjs.com/package/react-beautiful-dnd)
This one is keyboard accessible, but I am open to other ones as well!

**Comment by rrrrrrockpang** [comment]
<img width="1008" alt="Screen Shot 2024-06-30 at 1 01 02 AM" src="https://github.com/crescendochu/access-survey/assets/73901780/6f520a63-f077-4bb5-95ab-16f69d84ac47">

I think we need to change the wording for this question. See: https://github.com/crescendochu/access-survey/blob/893253a14f5e765009e9e237ff9726233c637fe9/src/survey/Questions/RankQuestion.js#L45

**Comment by rrrrrrockpang** [comment]
@crescendochu once wording is fixed, this issue can be closed.

**Comment by crescendochu** [comment]
Yayyyy nicely done! I also tried the drag and drop can be done with keyboard control.
Just one thing, can we have a number next to the tabs? Like the example in Typeform [https://0c241h8elga.typeform.com/to/ZOEfkMKl](https://0c241h8elga.typeform.com/to/ZOEfkMKl).

**Comment by rrrrrrockpang** [comment]
See 2c869c3. Issue fully resolved.
